image: docker:stable
services:
  - docker:stable-dind

stages:
  - laravel
  - mailhog
  - nginx
  - php

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

laravel-echo:
  stage: laravel
  needs: []
  script:
    - docker pull $CI_REGISTRY/6go-srl/docker/laravel-echo:1.0 || true
    - docker build --cache-from $CI_REGISTRY/6go-srl/docker/laravel-echo:1.0 -t $CI_REGISTRY/6go-srl/docker/laravel-echo:1.0 ./laravel-echo/
    - docker push $CI_REGISTRY/6go-srl/docker/laravel-echo:1.0

mailhog-latest:
  stage: mailhog
  needs: []
  script:
    - docker pull $CI_REGISTRY/6go-srl/docker/mailhog:latest || true
    - docker build --cache-from $CI_REGISTRY/6go-srl/docker/mailhog:latest -t $CI_REGISTRY/6go-srl/docker/mailhog:latest ./mailhog/
    - docker push $CI_REGISTRY/6go-srl/docker/mailhog:latest

nginx-1.19:
  stage: nginx
  needs: []
  script:
    - docker pull $CI_REGISTRY/6go-srl/docker/nginx:1.19 || true
    - docker build --cache-from $CI_REGISTRY/6go-srl/docker/nginx:1.19 -t $CI_REGISTRY/6go-srl/docker/nginx:1.19 ./nginx/
    - docker push $CI_REGISTRY/6go-srl/docker/nginx:1.19

php-7.4:
  stage: php
  needs: []
  script:
    - docker pull $CI_REGISTRY/6go-srl/docker/php:7.4 || true
    - docker build --cache-from $CI_REGISTRY/6go-srl/docker/php:7.4 -t $CI_REGISTRY/6go-srl/docker/php:7.4 ./php/7.4/
    - docker push $CI_REGISTRY/6go-srl/docker/php:7.4

php-8.0:
  stage: php
  needs: []
  script:
    - docker pull $CI_REGISTRY/6go-srl/docker/php:8.0 || true
    - docker build --cache-from $CI_REGISTRY/6go-srl/docker/php:8.0 -t $CI_REGISTRY/6go-srl/docker/php:8.0 ./php/8.0/
    - docker push $CI_REGISTRY/6go-srl/docker/php:8.0
